#!/bin/sh

GH_USER=agustim
GH_REPO=package-serf

curl "https://codeload.github.com/${GH_USER}/${GH_REPO}/zip/master" > ${GH_REPO}.zip
unzip ${GH_REPO}.zip 
cd ${GH_REPO}-master/
make install
cd ..
rm -rf ${GH_REPO}-master ${GH_REPO}.zip 

