#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          etcd
# Required-Start:    $local_fs $remote_fs $network $syslog $named 
# Required-Stop:     $local_fs $remote_fs $network $syslog $named 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/Stop A highly-available key value store for shared configuration and service discovery
### END INIT INFO

NAME=etcd
ETCDPATH="/opt/etcd"
ETCDBIN="$ETCDPATH/$NAME"
CONFFILE="/etc/avahi-ps-etcd.conf"
PIDFILE="/var/run/etcd.pid"

BIND_IP="0.0.0.0"
MACHINE=$(uname -n)
OPTS=""
SERVER_ETCD_BASE="127.0.0.1:4001"
ETCD_PEER_PORT="7001"
ETCD_PORT="4001"
ETCD_LOG="/dev/null"

test -f $CONFFILE && . $CONFFILE

GTCONF="/etc/getinconf-client.conf"
test -f $GTCONF && . $GTCONF || exit 0

[ -z "$ETCD_CONNECT" ] &&  PEERS="" || PEERS="-peers $ETCD_CONNECT"
PUBLIC_DEVICE=${INTERNAL_DEV}
PUBLIC_IP=$(ip addr show dev $PUBLIC_DEVICE|grep "global $PUBLIC_DEVICE\$"|awk '{print $2}'|awk -F "/" {'print $1'})

start() {
	[ ! -f $ETCDBIN ] && { echo "etcd is not installed in $ETCDBIN."; exit 0; }
	mkdir -p $ETCDPATH/machines/
	$ETCDBIN -peer-bind-addr ${PUBLIC_IP}:${ETCD_PEER_PORT} -peer-addr ${PUBLIC_IP}:${ETCD_PEER_PORT} -bind-addr ${BIND_IP}:${ETCD_PORT} -addr ${BIND_IP}:${ETCD_PORT} $PEERS -data-dir $ETCDPATH/machines -name $MACHINE $OPTS >> $ETCD_LOG 2>&1 & 
	echo $! > $PIDFILE  
}
stop() {
  kill -9 $(cat $PIDFILE)
  rm $PIDFILE
}
restart() {
  stop
  sleep 0.5
  start
}

case "$1" in
  start)
    start
  ;;
  stop)
    stop
  ;;
  restart)
    restart
  ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}"
    exit 1
  ;;
esac

exit 0


